Change to modified gitflow
Change gitflow to work with semantic versioning tools

diff --git a/git-flow-hotfix b/git-flow-hotfix
--- a/git-flow-hotfix
+++ b/git-flow-hotfix
@@ -40,7 +40,6 @@ init() {
   require_git_repo
   require_gitflow_initialized
   gitflow_load_settings
-  VERSION_PREFIX=$(eval "echo `git config --get gitflow.prefix.versiontag`")
   PREFIX=$(git config --get gitflow.prefix.hotfix)
 }
 
@@ -130,6 +129,7 @@ parse_args() {
 	# read arguments into global variables
 	VERSION=$1
 	BRANCH=$PREFIX$VERSION
+	BASE=${2:-$MASTER_BRANCH}
 }
 
 require_version_arg() {
@@ -158,16 +158,19 @@ require_no_existing_hotfix_branches() {
 
 cmd_start() {
 	DEFINE_boolean fetch false "fetch from $ORIGIN before performing finish" F
+	DEFINE_boolean forceversion false "don't validate the release branch version" a
 	parse_args "$@"
-	BASE=${2:-$MASTER_BRANCH}
 	require_version_arg
+	if noflag forceversion; then
+		validate_version_arg "$VERSION"
+	fi
 	require_base_is_on_master
 	require_no_existing_hotfix_branches
 
 	# sanity checks
 	require_clean_working_tree
 	require_branch_absent "$BRANCH"
-	require_tag_absent "$VERSION_PREFIX$VERSION"
+	require_tag_absent "$VERSION"
 	if flag fetch; then
 		git_do fetch -q "$ORIGIN" "$MASTER_BRANCH"
 	fi
@@ -177,14 +180,16 @@ cmd_start() {
 
 	# create branch
 	git_do checkout -b "$BRANCH" "$BASE"
+	git_do commit --allow-empty --quiet -m "Starting hotfix $VERSION"
+	git_do tag -a -m "Starting hotfix $VERSION" "$VERSION-hotfix"
 
 	echo
 	echo "Summary of actions:"
 	echo "- A new branch '$BRANCH' was created, based on '$BASE'"
 	echo "- You are now on branch '$BRANCH'"
+	echo "- $BRANCH was tagged"
 	echo
 	echo "Follow-up actions:"
-	echo "- Bump the version number now!"
 	echo "- Start committing your hot fixes"
 	echo "- When done, run:"
 	echo
@@ -287,14 +292,18 @@ cmd_finish() {
 		# try to tag the release
 		# in case a previous attempt to finish this release branch has failed,
 		# but the tag was set successful, we skip it now
-		local tagname=$VERSION_PREFIX$VERSION
+		local tagname=$VERSION
 		if ! git_tag_exists "$tagname"; then
 			local opts="-a"
 			flag sign && opts="$opts -s"
 			[ "$FLAGS_signingkey" != "" ] && opts="$opts -u '$FLAGS_signingkey'"
-			[ "$FLAGS_message" != "" ] && opts="$opts -m '$FLAGS_message'"
+			if [ "$FLAGS_message" != "" ]; then
+				opts="$opts -m '$FLAGS_message'"
+			else
+				opts="$opts -m 'Merging $VERSION back to $MASTER_BRANCH'"
+			fi
 			[ "$FLAGS_messagefile" != "" ] && opts="$opts -F '$FLAGS_messagefile'"
-			eval git_do tag $opts "$VERSION_PREFIX$VERSION" "$BRANCH" || \
+			eval git_do tag $opts "$tagname" || \
 			die "Tagging failed. Please run finish again to retry."
 		fi
 	fi
@@ -311,6 +320,16 @@ cmd_finish() {
 		git_do merge --no-ff "$BRANCH" || \
 		  die "There were merge conflicts."
 		  # TODO: What do we do now?
+	fi
+
+	local dev_tagname="$(increment_patch_version_by_one $VERSION)-dev"
+	if ! git_tag_exists "$dev_tagname"; then
+		# try to tag the develop branch with version-dev
+		# in case a previous attempt to finish this release branch has failed,
+		# but the tag was set successful, we skip it now
+		git_do checkout "$DEVELOP_BRANCH"
+		git_do tag -a -m "Merging $VERSION back to $DEVELOP_BRANCH" "$dev_tagname" || \
+		die "Tagging $DEVELOP_BRANCH failed. Please run finish again to retry."
 	fi
 
 	# delete branch
@@ -334,9 +353,10 @@ cmd_finish() {
 	echo "- Latest objects have been fetched from '$ORIGIN'"
 	echo "- Hotfix branch has been merged into '$MASTER_BRANCH'"
 	if noflag notag; then
-		echo "- The hotfix was tagged '$VERSION_PREFIX$VERSION'"
+		echo "- The hotfix was tagged '$VERSION'"
 	fi
 	echo "- Hotfix branch has been back-merged into '$DEVELOP_BRANCH'"
+	echo "- $DEVELOP_BRANCH has been tagged"
 	if flag keep; then
 		echo "- Hotfix branch '$BRANCH' is still available"
 	else
